[build]
  # 빌드 명령어
  command = "npm run build"
  # 빌드 결과물 디렉토리
  publish = "dist"

[build.environment]
  # Node.js 버전 지정
  NODE_VERSION = "18"

# SPA(Single Page Application)를 위한 리디렉션 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200